# Generated by Django 5.1.3 on 2024-12-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_candidate_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.CharField(choices=[('CANDIDATE', 'candidate'), ('RECRUITER', 'recruiter')], default='candidate', max_length=30),
        ),
    ]
