# Generated by Django 5.1.3 on 2024-11-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('working_arrangements', models.CharField(blank=True, max_length=150)),
                ('contract_type', models.CharField(blank=True, max_length=50)),
                ('date_job_start', models.DateField(blank=True, null=True)),
                ('requirements', models.JSONField(blank=True, default=list, null=True)),
                ('location', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
