# Generated by Django 5.1.3 on 2024-12-01 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('users', '0003_candidate_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='joboffers', to='users.recruiter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joboffer',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
