# Generated by Django 5.1.3 on 2024-12-01 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_joboffer_owner_joboffer_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joboffer',
            old_name='published',
            new_name='is_published',
        ),
    ]
